[package]
name = "tauri-lite-lib"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "1.0.109"
quote = "1.0.23"
darling = "0.14.3"